AllCops:
  NewCops: enable
  SuggestExtensions: false

# Better to be explicit with 'return' statements
Style/RedundantReturn:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false